CREATE TABLE IF NOT EXISTS clans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    gold BIGINT,
    CONSTRAINT pk_clan PRIMARY KEY (id),
    CONSTRAINT UQ_clan_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS persons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    gold BIGINT NOT NULL,
    CONSTRAINT pk_person PRIMARY KEY (id),
    CONSTRAINT UQ_person_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS clan_person (
    clan_id BIGINT REFERENCES clans(id),
    person_id BIGINT REFERENCES persons(id),
    CONSTRAINT pk_clan_person PRIMARY KEY (person_id, clan_id)
);

CREATE TABLE IF NOT EXISTS gold_operations
(
    operation_id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    clan_id                  BIGINT REFERENCES clans (id),
    person_id                BIGINT REFERENCES persons (id),
    amount                   BIGINT,
    operation_time           TIMESTAMP,
    initial_clan_gold_amount BIGINT NOT NULL,
    is_withdrawal            boolean
);